server:
  port: 8080
  error:
    include-message: always

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/spring_reactive
    username: postgres
    password: mahtab238

  flyway:
    enabled: true
    baseline-on-migrate: true
    url: jdbc:postgresql://localhost:5432/spring_reactive
    user: postgres
    password: mahtab238